### ISSUE TITLE
Problems with Playing the sender "Antenne Bayern"

### ISSUE THREAD

**Issue by JocB1** [karawin/Ka-Radio32#256]
Hi, 
generally, the project runs very reliably, only with the station "Antenne Bayern" I have since V1.9 the problem that the software crashes after 1-3 hours on this station. After that only a hardware-rest helps to restart.  
URL: https://s7-webradio.antenne.de:443/antenne/stream/mp3

I use 2x Maxim MAX98357 I2S Amplifiers in Stereo configuration.

**Comment by karawin** [comment]
Hi, 
I will try it. I think that the problem may be in the chunked received stream wrongly computed in some frames.

Try the simple non https   URL:http://s7-webradio.antenne.de:80/antenne/stream/mp3

**Comment by JocB1** [comment]
Hi,

 

it´s the same problem with the simple non https URL.

 

Gesendet: Freitag, 11. Februar 2022 um 15:30 Uhr
Von: "KaraWin" ***@***.***>
An: "karawin/Ka-Radio32" ***@***.***>
Cc: "JocB1" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [karawin/Ka-Radio32] Problems with Playing the sender "Antenne Bayern" (Issue #256)


 

Hi,
I will try it. I think that the problem may be in the chunked received stream wrongly computed in some frames.

Try the simple non https URL:http://s7-webradio.antenne.de:80/antenne/stream/mp3

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by karawin** [comment]
Corrected, thanks.
You can update now.

**Comment by Ant-12** [comment]
entry 0x400806d8
I (8) main: starting app_main()
I (8) main: RAM left: 4378048
E (18) partition: No MD5 found in partition table
assertion "it != NULL" failed: file "C:/msys32/home/jp/esp/esp-idf/components/app_update/esp_ota_ops.c", line 507, function: esp_ota_get_running_partition
abort() was called at PC 0x400f0a17 on core 0

ELF file SHA256: c185034d148c4940

Backtrace: 0x4008d0e3:0x3ffb2da0 0x4008d4d9:0x3ffb2dc0 0x400f0a17:0x3ffb2de0 0x4014818b:0x3ffb2e10 0x400d96b3:0x3ffb2e30 0x400d2ff4:0x3ffb2e90

**Comment by Ant-12** [comment]
If you have not updated the firmware for the last hour, then the solution to the problem for me was the reflashing partitions.bin 

What does "Change from IDF 4.4" mean? Are you migrating to IDF v4.4? Why not to IDF v5?

**Comment by karawin** [comment]
The only usable bin (with your correction) is from KaRadio32 on git hub or update from the "update now "button of the web or the sys.update on serial.

KaRadio32_4 is not operational and may be never will be. Memory problem
And I don' know why they changed the subtype default from 0 to 6 in idf4.4.
That's why the partition must be flashed depending of the idf release.
4.4 to be sure not to have to change all deprecated in a first time.

IDF 4.4:
 cmd.exe /C "cd /D C:\Users\jp\esp\KaRadio32_4\build && C:\Espressif\python_env\...works/esp-idf-v4.4/tools/idf_size.py C:/Users/jp/esp/KaRadio32_4/build/KaRadio32.map"Total sizes:
Used static DRAM:   81812 bytes (  98924 remain, 45.3% used)
      .data size:   43172 bytes
      .bss  size:   38640 bytes
Used static IRAM:  104463 bytes (  26609 remain, 79.7% used)
      .text size:  103436 bytes
   .vectors size:    1027 bytes
Used stat D/IRAM:  186275 bytes ( 125533 remain, 59.7% used)
      .data size:   43172 bytes
      .bss  size:   38640 bytes
      .text size:  103436 bytes
   .vectors size:    1027 bytes
Used Flash size : 1615107 bytes
      .text     : 1095863 bytes
      .rodata   :  518988 bytes
Total image size: 1910377 bytes (.bin may be padded larger)

IDF 3.3:
Total sizes:
 DRAM .data size:   17212 bytes
 DRAM .bss  size:   43416 bytes
Used static DRAM:   60628 bytes (  63952 available, 48.7% used)
Used static IRAM:   72960 bytes (  58112 available, 55.7% used)
      Flash code:  926514 bytes
    Flash rodata:  547520 bytes
Total image size:~1564206 bytes (.bin may be padded larger)

**Comment by Ant-12** [comment]
Look at Pilnikov's project:
https://github.com/pilnikov/Ka_mod
I got a firmware with a size of 1624496 bytes with using IDF v5.

**Comment by karawin** [comment]
Yes but it i a 
#define RELEASE "1.9"
#define REVISION "7"
Two years ago and without wolfssl.

I started from Ka_Mod and written all CMakeLists in order to retrieve the real components.
Now, working on memories optimization.

**Comment by Ant-12** [comment]
Yes. I know it.
Ka_Mod also has no S/PDIF output.
Maybe there need to check SDK configuration for new unused components?

**Comment by Ant-12** [comment]
Jean-Pierre, please do not ignore this:
https://github.com/karawin/KaRadio32_4/issues

**Comment by Ant-12** [comment]
Jean-Pierre, here I just remind you of comments on the commits.

**Comment by karawin** [comment]
> Hi,   it´s the same problem with the simple non https URL.   Gesendet: Freitag, 11. Februar 2022 um 15:30 Uhr Von: "KaraWin" ***@***.***> An: "karawin/Ka-Radio32" ***@***.***> Cc: "JocB1" ***@***.***>, "Author" ***@***.***> Betreff: Re: [karawin/Ka-Radio32] Problems with Playing the sender "Antenne Bayern" (Issue #256)   Hi, I will try it. I think that the problem may be in the chunked received stream wrongly computed in some frames. Try the simple non https URL:http://s7-webradio.antenne.de:80/antenne/stream/mp3 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

Corrected now.
Closing
