### ISSUE TITLE
How to connect an external dac?

### ISSUE THREAD

**Issue by Primus007** [karawin/Ka-Radio32#31]
I have these i2s DAC PCM5102 : https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpYA78Iu82clSBfF2pIcEeZu833MCSysnCvBmpJKYrZIjsyMvTjA

I have:
DAC    ESP32
---------------
BCK     Gpio26
LCK     Gpio25
DIN     Gpio22
Power:
3,3v  +  to ESP Vin and DAC VCC
3,3v  -   to ESP GND and DAC GND

The Settings in KaRadio set to i2s Output

My PCM5102 is well wired. On other Applications it works well.
Esp32 is connectet to a station. Volume is on 200
But in KaRadio comes no sound :(

Anyone can help me please?

**Comment by HIMjack666** [comment]
Try ESP Vin connect to DAC VCC and plug ESP in USB port, better power bank.

**Comment by Primus007** [comment]
Thank you. Works good.

**Comment by joaofl** [comment]
@Primus007 
I also have one of these DAC based on the **PCM5102**. More specifically I have a [board](https://www.aliexpress.com/item/TTGO-ESP32-Tm-Music-albums-2-4-inch-TFT-PCM5102A-SD-WiFi-Module-Bluetooth-development-board/32848902211.html?spm=a2g0s.9042311.0.0.6e444c4d6M7uWZ) that comes with the DAC, LCD and battery support. 

The issue is that when I configure the KaRadio to use the proper IOs, and the I2S output, I get some audio output, but I get **music playing really fast and noisy**, like if it was playing in fast forward.

I've been looking around for any possible cause, but could not really figure it out so far. Which IDF and SDK versions are you using? Did you need to change any other config to get it working?

**Comment by pilnikov** [comment]
For TTGO TM try my fork https://github.com/pilnikov/KaRadio32_fork

**Comment by pilnikov** [comment]
I modified gpio.h (for correct connection) addon.c (to display Russian on the screen) and disabled the unused RDA module. Maybe it's really in the new IDF? I've make my firmware for a long time ago.

**Comment by joaofl** [comment]
@pilnikov 
Yes. I've merged those exact changes on this code here, and it does not work. The music plays in fast-forward. Some issue with rates. Really dont know what. Do you think you can test it again and see if you find something?

**Comment by pilnikov** [comment]
ok! i try it. Maybe tommorow.

**Comment by pilnikov** [comment]
I used the current (on March) version of IDF (3 months ago was March)

**Comment by joaofl** [comment]
That's strange.. By merging the code you have on your repo with this one here, I swear it doesnt work. Unless you changed something else on the **sdkconfig** file, or any other config at runtime.

Let me know please.

**Comment by pilnikov** [comment]
https://yadi.sk/d/AYk_Jhi13Xqi78 full project include idf, exclude msys. need corrected path

**Comment by joaofl** [comment]
Tried to compile, but could not. Some weird errors... Really lost on this topic
